#!/bin/ksh -e
PWD=$(cd $(dirname $0) && pwd)

ln -s $PWD/bin ~ || true

ls -a | tail +3 | sed -n '/^[^.]*\..*$/p' | \
	sed -n '/.git/!p' | while read path
do
	relpath=${path##$PWD/}
	if [[ -d $relpath ]]; then
		[[ -d ~/$relpath ]] || mkdir ~/$relpath
		ls $relpath | while read child; do \
			ln -s $PWD/$relpath/$child ~/$relpath || true; done
	else
		ln -s $PWD/$relpath ~/$relpath || true
	fi
done
