#!/bin/ksh
set -e

ln -fs $PWD/.vimrc $PWD/.profile $PWD/.kshrc ~
mkdir -p ~/.vim/autoload ~/.vim/bundle || true
ln -sf $PWD/.vim/ftplugin $PWD/.vim/colors ~/.vim
[ -e $HOME/.vim/autoload/pathogen.vim ] ||
	curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

iplug(){ 
	name=`basename $1`
	target=$HOME/.vim/bundle/$name
	if [[ -e $target ]]; then
		git -C $target pull
	else
		git -C ~/.vim/bundle clone git://github.com/$1 
	fi
}

iplug 'tpope/vim-unimpaired'
iplug 'tpope/vim-surround'
iplug 'tpope/vim-fugitive'
iplug 'tpope/vim-commentary'
iplug 'tpope/vim-vinegar'
iplug 'tpope/vim-dispatch'
