#!/bin/ksh


ln -fs $PWD/.vimrc $PWD/.profile $PWD/.kshrc ~
mkdir -p ~/.vim/autoload ~/.vim/bundle || true
ln -sf $PWD/.vim/ftplugin $PWD/.vim/colors ~/.vim
[ -e $HOME/.vim/autoload/pathogen.vim ] ||
	curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

bundle=$HOME/.vim/bundle
not=
while read -r line; do
	name=$(basename $line)
	target=$bundle/$name
	not=$not"\! -path '/**/$name' -a "
	if [[ -e $target ]]; then
		git -C $target pull
	else
		git -C $bundle clone https://github.com/$line
	fi
done << EOF
tpope/vim-unimpaired
tpope/vim-surround
tpope/vim-fugitive
tpope/vim-commentary
tpope/vim-vinegar
sjl/gundo.vim
EOF

# python 2.4+
# sjl/gundo.vim

echo -n "proceeding will delete all other bundles (y/*) "
read -r y
[ "$y" == "y" ] && eval find $bundle -mindepth 1 -maxdepth 1 -type d \
	${not%???} | while read -r path; do
		echo rm -rf $path
		rm -rf $path
	done
