#!/bin/ksh -e

f="kill 0;"

bspc monitor -d 0 1 2 3 4 5 6 7 8 9

while read line; do
	bspc config $line
done <<EOF
focused_border_color `xg color13`
normal_border_color `xg color0`
border_width 1
window_gap 0
split_ratio 0.50
borderless_monocle true
gapless_monocle true
single_monocle true
click_to_focus true
EOF

bspc config external_rules_command `which bspwm_external`
panel &
f=$f"kill $!;"
sxhkd &
f=$f"kill $!"

trap "$f" INT
wait
